name: Testowanie kodu za pomocą PyLint
on:
  push:
    branches:
      - main  # Zmień na nazwę swojej głównej gałęzi, jeśli jest inna
  pull_request:
    branches:
      - main  # Zmień na nazwę swojej głównej gałęzi, jeśli jest inna
      -
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repozytorium
        uses: actions/checkout@v2
      - name: Skonfiguruj Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Wybierz wersję Pythona, której chcesz użyć
      - name: Zainstaluj zależności
        run: pip install pylint
      - name: Uruchom PyLint
        run: pylint your_code.py  # Zastąp `your_code.py` nazwą pliku lub katalogu, który chcesz przetestować