# .github/workflows/test_action.yaml
name: Get Version
on: [push]

jobs:
  check-python-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Config Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Show Python Version

        run: python --version